export const URL_DETAIL = 'https://api.themoviedb.org/3/movie/';
export const URL_SEARCH = 'https://api.themoviedb.org/3/search/movie?query=';
export const URL_IMAGE = 'https://image.tmdb.org/t/p/w500/';
export const URL_BACKGROUND = 'https://image.tmdb.org/t/p/original';
export const API_KEY = '?api_key=320a50358c05fc0dab60872ae9cc4b74';
export const API_KEY_ALT = '&api_key=320a50358c05fc0dab60872ae9cc4b74';
export const IMG_SIZE_XSMALL = 'https://image.tmdb.org/t/p/w45/';
export const VIDEO_LINK = 'https://api.themoviedb.org/3/movie/';
export const IMAGE_BASE_URL ='http://image.tmdb.org/t/p/';
export const BACKDROP_SIZE = 'w1280';
export const API_URL = 'https://api.themoviedb.org/3/';
